In [41]:
# 必要なライブラリをインポート
import pandas as pd
import os

# --- 1. データの読み込み ---
cleaned_data_path = '../data/processed/cleaned_data.parquet'
df = pd.read_parquet(cleaned_data_path)

In [42]:
#建築年を西暦に
# '戦前'を1945に変換
df['建築年'] = df['建築年'].replace('戦前', 1945)
def convert_wareki_to_seireki(wareki):
    """
    和暦を西暦に変換する関数
    """
    if pd.isna(wareki):
        return None

    wareki = str(wareki).strip()
    
    # 昭和
    if '昭和' in wareki:
        year_str = wareki.replace('昭和', '').replace('年', '')
        try:
            year = int(year_str)
            return 1925 + year
        except ValueError:
            return None
    
    # 平成
    elif '平成' in wareki:
        year_str = wareki.replace('平成', '').replace('年', '')
        try:
            year = int(year_str)
            return 1988 + year
        except ValueError:
            return None
    
    # 令和
    elif '令和' in wareki:
        year_str = wareki.replace('令和', '').replace('年', '')
        try:
            year = int(year_str)
            return 2018 + year
        except ValueError:
            return None
    
    # 大正
    elif '大正' in wareki:
        year_str = wareki.replace('大正', '').replace('年', '')
        try:
            year = int(year_str)
            return 1911 + year
        except ValueError:
            return None
            
    # 明治
    elif '明治' in wareki:
        year_str = wareki.replace('明治', '').replace('年', '')
        try:
            year = int(year_str)
            return 1867 + year
        except ValueError:
            return None

    # 和暦でない場合はそのまま返すか、NaNにする
    return None

df['建築年'] = df['建築年'].apply(convert_wareki_to_seireki)

#取引時点を西暦に
df['取引時点'] = df['取引時点'].str.extract(r'(\d{4})').astype(float)

#取引時点での築年数の追加
df['取引時点での築年数'] = df['取引時点'] - df['建築年']


#欠損値削除
df.dropna(subset=['取引時点での築年数'], inplace=True)

In [43]:
import re
# 新しく追加する人口密度のテキストデータ
density_text = """
1東京都6,451.17
2大阪府4,603.02
3神奈川県3,816.89
4埼玉県1,929.89
5愛知県1,443.06
6千葉県1,217.00
7福岡県1,022.06
8沖縄県642.85
9兵庫県635.26
10京都府546.65
11香川県488.61
12茨城県460.79
13静岡県453.15
14滋賀県348.69
15奈良県348.18
16佐賀県322.73
17広島県320.44
18宮城県308.58
19長崎県302.75
20群馬県296.97
21三重県296.37
22栃木県293.74
23石川県262.42
24岡山県257.31
25富山県234.48
26熊本県228.92
27愛媛県224.70
28山口県209.32
29和歌山県186.18
30岐阜県180.12
31山梨県176.97
32福井県176.27
33大分県171.15
34新潟県166.79
35鹿児島県166.58
36徳島県165.27
37鳥取県151.43
38長野県146.62
39宮崎県133.35
40福島県126.40
41青森県120.76
42山形県108.42
43島根県95.62
44高知県92.32
45秋田県77.02
46岩手県74.92
47北海道64.29
"""

# --- Step 2: 人口密度データを整形してデータフレームを作成 ---

prefectures_density = []
densities = []

# テキストを行ごとに分割して処理
for line in density_text.strip().split('\n'):
    # 正規表現で都道府県名と数値を抽出
    match = re.search(r'\d+([^\d,.]+)\s*([\d,.]+)', line)
    if match:
        prefecture = match.group(1).strip()
        density_str = match.group(2)

        # コンマを削除して浮動小数点数に変換
        density_float = float(density_str.replace(',', ''))

        prefectures_density.append(prefecture)
        densities.append(density_float)

# 人口密度のデータフレームを作成
density_df = pd.DataFrame({
    '都道府県名': prefectures_density,
    '人口密度': densities
})


# --- Step 3: 最終的な結合 ---

# 坪単価が入ったdfに、さらに人口密度のデータを結合
df = pd.merge(df, density_df, on='都道府県名', how='left')
df

,ID,種類,市区町村コード,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,間取り,面積（㎡）,...,今後の利用目的,都市計画,建ぺい率（％）,容積率（％）,取引時点,改装,取引の事情等,取引価格（総額）_log,取引時点での築年数,人口密度
0,1060685,中古マンション等,1108,北海道,札幌市厚別区,大谷地東,大谷地,8.0,３ＬＤＫ,80,...,None,準工業地域,60.0,200.0,2009.0,未改装,None,7.079181,14.0,64.29
1,1005580,中古マンション等,1101,北海道,札幌市中央区,南９条西,中島公園,5.0,１ＤＫ,30,...,住宅,近隣商業地域,80.0,300.0,2018.0,未改装,None,6.755875,36.0,64.29
2,1001363,中古マンション等,1101,北海道,札幌市中央区,北３条西,西１１丁目,11.0,３ＬＤＫ,65,...,None,近隣商業地域,80.0,300.0,2010.0,未改装,None,7.204120,19.0,64.29
3,1052374,中古マンション等,1108,北海道,札幌市厚別区,厚別中央２条,ひばりが丘(北海道),5.0,４ＬＤＫ,90,...,住宅,商業地域,80.0,400.0,2015.0,未改装,None,7.591065,0.0,64.29
4,1059107,中古マンション等,1108,北海道,札幌市厚別区,厚別東４条,新さっぽろ,12.0,４ＬＤＫ,80,...,None,準工業地域,60.0,200.0,2012.0,未改装,None,6.875061,30.0,64.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551640,47001698,中古マンション等,47201,沖縄県,那覇市,松島,市立病院前(沖縄),3.0,４ＬＤＫ,80,...,住宅,第１種住居地域,60.0,200.0,2017.0,改装済,None,7.518514,10.0,642.85
551641,47030340,中古マンション等,47201,沖縄県,那覇市,前島,美栄橋,4.0,２ＤＫ,40,...,None,商業地域,80.0,400.0,2008.0,未改装,None,5.832509,24.0,642.85
551642,47000640,中古マンション等,47201,沖縄県,那覇市,字国場,壺川,29.0,３ＬＤＫ,65,...,住宅,第１種中高層住居専用地域,60.0,200.0,2018.0,改装済,None,7.301030,22.0,642.85
551643,47014718,中古マンション等,47201,沖縄県,那覇市,小禄,奥武山公園,15.0,３ＬＤＫ,65,...,住宅,第２種中高層住居専用地域,60.0,200.0,2014.0,未改装,None,7.322219,9.0,642.85
551644,47001601,中古マンション等,47201,沖縄県,那覇市,松尾,県庁前(沖縄),12.0,４ＬＤＫ,80,...,その他,商業地域,80.0,400.0,2018.0,未改装,None,7.342423,4.0,642.85

In [44]:
import os
os.getcwd()
# The 'r' before the string makes it a "raw" string
os.chdir(r'C:\Users\sabri\Downloads\マンション価格予測\data')

#市区町村別の人口密度
df_mitudo = pd.read_csv('市区町村別人口密度.csv')
# 結合キーの列名
merge_key = '市区町村コード'

# 結合の実行
df = pd.merge(df, df_mitudo, on=merge_key, how='left')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551645 entries, 0 to 551644
Data columns (total 24 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            551645 non-null  int64
 1   種類            551645 non-null  object
 2   市区町村コード       551645 non-null  int64
 3   都道府県名         551645 non-null  object
 4   市区町村名         551645 non-null  object
 5   地区名           551436 non-null  object
 6   最寄駅：名称        551645 non-null  object
 7   最寄駅：距離（分）     551645 non-null  float64
 8   間取り           534244 non-null  object
 9   面積（㎡）         551645 non-null  int64
 10  建築年           551645 non-null  float64
 11  建物の構造         545235 non-null  object
 12  用途            511944 non-null  object
 13  今後の利用目的       246839 non-null  object
 14  都市計画          551547 non-null  object
 15  建ぺい率（％）       551645 non-null  float64
 16  容積率（％）        551645 non-null  float64
 17  取引時点          551645 non-null  float64
 18  改装            504294 non-null  object
 19  取引の事情等        14670 non-null   object
 20  取引価格（総額）_log  551645 non-null  float64
 21  取引時点での築年数     551645 non-null  float64
 22  人口密度          551645 non-null  float64
 23  市区町村人口密度      551645 non-null  float64
dtypes: float64(9), int64(3), object(12)
memory usage: 101.0+ MB

,ID,種類,市区町村コード,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,間取り,面積（㎡）,...,都市計画,建ぺい率（％）,容積率（％）,取引時点,改装,取引の事情等,取引価格（総額）_log,取引時点での築年数,人口密度,市区町村人口密度
0,1060685,中古マンション等,1108,北海道,札幌市厚別区,大谷地東,大谷地,8.0,３ＬＤＫ,80,...,準工業地域,60.0,200.0,2009.0,未改装,None,7.079181,14.0,64.29,7398.9
1,1005580,中古マンション等,1101,北海道,札幌市中央区,南９条西,中島公園,5.0,１ＤＫ,30,...,近隣商業地域,80.0,300.0,2018.0,未改装,None,6.755875,36.0,64.29,10660.3
2,1001363,中古マンション等,1101,北海道,札幌市中央区,北３条西,西１１丁目,11.0,３ＬＤＫ,65,...,近隣商業地域,80.0,300.0,2010.0,未改装,None,7.204120,19.0,64.29,10660.3
3,1052374,中古マンション等,1108,北海道,札幌市厚別区,厚別中央２条,ひばりが丘(北海道),5.0,４ＬＤＫ,90,...,商業地域,80.0,400.0,2015.0,未改装,None,7.591065,0.0,64.29,7398.9
4,1059107,中古マンション等,1108,北海道,札幌市厚別区,厚別東４条,新さっぽろ,12.0,４ＬＤＫ,80,...,準工業地域,60.0,200.0,2012.0,未改装,None,6.875061,30.0,64.29,7398.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551640,47001698,中古マンション等,47201,沖縄県,那覇市,松島,市立病院前(沖縄),3.0,４ＬＤＫ,80,...,第１種住居地域,60.0,200.0,2017.0,改装済,None,7.518514,10.0,642.85,8184.6
551641,47030340,中古マンション等,47201,沖縄県,那覇市,前島,美栄橋,4.0,２ＤＫ,40,...,商業地域,80.0,400.0,2008.0,未改装,None,5.832509,24.0,642.85,8184.6
551642,47000640,中古マンション等,47201,沖縄県,那覇市,字国場,壺川,29.0,３ＬＤＫ,65,...,第１種中高層住居専用地域,60.0,200.0,2018.0,改装済,None,7.301030,22.0,642.85,8184.6
551643,47014718,中古マンション等,47201,沖縄県,那覇市,小禄,奥武山公園,15.0,３ＬＤＫ,65,...,第２種中高層住居専用地域,60.0,200.0,2014.0,未改装,None,7.322219,9.0,642.85,8184.6
551644,47001601,中古マンション等,47201,沖縄県,那覇市,松尾,県庁前(沖縄),12.0,４ＬＤＫ,80,...,商業地域,80.0,400.0,2018.0,未改装,None,7.342423,4.0,642.85,8184.6

In [45]:
#取引事情ダミー化'取引の事情等_関係者間取引''取引の事情等_調停・競売等''取引の事情等_その他'←この三つをモデルに入れる
df=pd.get_dummies(df, columns=['取引の事情等'], dtype=int)
df['取引の事情等_その他']=df['取引の事情等_その他事情有り']+df['取引の事情等_他の権利・負担付き']
+df['取引の事情等_他の権利・負担付き、調停・競売等']+df['取引の事情等_瑕疵有りの可能性']+df['取引の事情等_調停・競売等、瑕疵有りの可能性']
+df['取引の事情等_関係者間取引、瑕疵有りの可能性']+df['取引の事情等_関係者間取引、調停・競売等']

0         0
1         0
2         0
3         0
4         0
         ..
551640    0
551641    0
551642    0
551643    0
551644    0
Length: 551645, dtype: int32

In [46]:
df=pd.get_dummies(df,columns=["改装"],dtype=int)
df

,ID,種類,市区町村コード,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,間取り,面積（㎡）,...,取引の事情等_他の権利・負担付き、調停・競売等,取引の事情等_瑕疵有りの可能性,取引の事情等_調停・競売等,取引の事情等_調停・競売等、瑕疵有りの可能性,取引の事情等_関係者間取引,取引の事情等_関係者間取引、瑕疵有りの可能性,取引の事情等_関係者間取引、調停・競売等,取引の事情等_その他,改装_改装済,改装_未改装
0,1060685,中古マンション等,1108,北海道,札幌市厚別区,大谷地東,大谷地,8.0,３ＬＤＫ,80,...,0,0,0,0,0,0,0,0,0,1
1,1005580,中古マンション等,1101,北海道,札幌市中央区,南９条西,中島公園,5.0,１ＤＫ,30,...,0,0,0,0,0,0,0,0,0,1
2,1001363,中古マンション等,1101,北海道,札幌市中央区,北３条西,西１１丁目,11.0,３ＬＤＫ,65,...,0,0,0,0,0,0,0,0,0,1
3,1052374,中古マンション等,1108,北海道,札幌市厚別区,厚別中央２条,ひばりが丘(北海道),5.0,４ＬＤＫ,90,...,0,0,0,0,0,0,0,0,0,1
4,1059107,中古マンション等,1108,北海道,札幌市厚別区,厚別東４条,新さっぽろ,12.0,４ＬＤＫ,80,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551640,47001698,中古マンション等,47201,沖縄県,那覇市,松島,市立病院前(沖縄),3.0,４ＬＤＫ,80,...,0,0,0,0,0,0,0,0,1,0
551641,47030340,中古マンション等,47201,沖縄県,那覇市,前島,美栄橋,4.0,２ＤＫ,40,...,0,0,0,0,0,0,0,0,0,1
551642,47000640,中古マンション等,47201,沖縄県,那覇市,字国場,壺川,29.0,３ＬＤＫ,65,...,0,0,0,0,0,0,0,0,1,0
551643,47014718,中古マンション等,47201,沖縄県,那覇市,小禄,奥武山公園,15.0,３ＬＤＫ,65,...,0,0,0,0,0,0,0,0,0,1
551644,47001601,中古マンション等,47201,沖縄県,那覇市,松尾,県庁前(沖縄),12.0,４ＬＤＫ,80,...,0,0,0,0,0,0,0,0,0,1

In [47]:
# 間取り

# '間取り' 列が NaN の行を削除

# 1. 欠損値を一時的に埋める
df["間取り_filled"] = df["間取り"].fillna("欠損値")

# 2. 頻度を計算する (新しい'間取り_filled'列に対して)
freq = df["間取り_filled"].value_counts()

# 3. グループ化の適用
df["間取り_grouped"] = df["間取り_filled"].apply(lambda x: x if freq[x] > 1000 else "その他")

# (Optional: 元のデータフレームから一時列を削除)
df = df.drop(columns=["間取り_filled"])

# # 3. ダミー変数化（0/1化）
df = pd.get_dummies(df, columns=["間取り_grouped"], dtype=int)

df.head()

,ID,種類,市区町村コード,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,間取り,面積（㎡）,...,間取り_grouped_１ＬＤＫ,間取り_grouped_１Ｒ,間取り_grouped_２ＤＫ,間取り_grouped_２Ｋ,間取り_grouped_２ＬＤＫ,間取り_grouped_２ＬＤＫ＋Ｓ,間取り_grouped_３ＤＫ,間取り_grouped_３ＬＤＫ,間取り_grouped_４ＤＫ,間取り_grouped_４ＬＤＫ
0,1060685,中古マンション等,1108,北海道,札幌市厚別区,大谷地東,大谷地,8.0,３ＬＤＫ,80,...,0,0,0,0,0,0,0,1,0,0
1,1005580,中古マンション等,1101,北海道,札幌市中央区,南９条西,中島公園,5.0,１ＤＫ,30,...,0,0,0,0,0,0,0,0,0,0
2,1001363,中古マンション等,1101,北海道,札幌市中央区,北３条西,西１１丁目,11.0,３ＬＤＫ,65,...,0,0,0,0,0,0,0,1,0,0
3,1052374,中古マンション等,1108,北海道,札幌市厚別区,厚別中央２条,ひばりが丘(北海道),5.0,４ＬＤＫ,90,...,0,0,0,0,0,0,0,0,0,1
4,1059107,中古マンション等,1108,北海道,札幌市厚別区,厚別東４条,新さっぽろ,12.0,４ＬＤＫ,80,...,0,0,0,0,0,0,0,0,0,1

In [48]:

print("--- 特徴量作成後のデータ ---")
print(df.head())

# --- 3. 処理後のデータを保存 ---
processed_dir = '../data/processed/'
processed_file = 'features.parquet' # モデル学習用の最終データ
processed_path = os.path.join(processed_dir, processed_file)

df.to_parquet(processed_path, index=False)

print(f"\n特徴量作成後のデータを {processed_path} に保存しました。")

--- 特徴量作成後のデータ ---
        ID        種類  市区町村コード 都道府県名   市区町村名     地区名      最寄駅：名称  最寄駅：距離（分）  \
0  1060685  中古マンション等     1108   北海道  札幌市厚別区    大谷地東         大谷地        8.0
1  1005580  中古マンション等     1101   北海道  札幌市中央区    南９条西        中島公園        5.0
2  1001363  中古マンション等     1101   北海道  札幌市中央区    北３条西       西１１丁目       11.0
3  1052374  中古マンション等     1108   北海道  札幌市厚別区  厚別中央２条  ひばりが丘(北海道)        5.0
4  1059107  中古マンション等     1108   北海道  札幌市厚別区   厚別東４条       新さっぽろ       12.0

    間取り  面積（㎡）  ...  間取り_grouped_１ＬＤＫ 間取り_grouped_１Ｒ 間取り_grouped_２ＤＫ  \
0  ３ＬＤＫ     80  ...                 0              0               0
1   １ＤＫ     30  ...                 0              0               0
2  ３ＬＤＫ     65  ...                 0              0               0
3  ４ＬＤＫ     90  ...                 0              0               0
4  ４ＬＤＫ     80  ...                 0              0               0

  間取り_grouped_２Ｋ 間取り_grouped_２ＬＤＫ  間取り_grouped_２ＬＤＫ＋Ｓ  間取り_grouped_３ＤＫ  \
0              0                0                   0                0
1              0                0                   0                0
2              0                0                   0                0
3              0                0                   0                0
4              0                0                   0                0

   間取り_grouped_３ＬＤＫ  間取り_grouped_４ＤＫ  間取り_grouped_４ＬＤＫ
0                 1                0                 0
1                 0                0                 0
2                 1                0                 0
3                 0                0                 1
4                 0                0                 1

[5 rows x 49 columns]

特徴量作成後のデータを ../data/processed/features.parquet に保存しました。

In [49]:
df.columns

Index(['ID', '種類', '市区町村コード', '都道府県名', '市区町村名', '地区名', '最寄駅：名称', '最寄駅：距離（分）',
       '間取り', '面積（㎡）', '建築年', '建物の構造', '用途', '今後の利用目的', '都市計画', '建ぺい率（％）',
       '容積率（％）', '取引時点', '取引価格（総額）_log', '取引時点での築年数', '人口密度', '市区町村人口密度',
       '取引の事情等_その他事情有り', '取引の事情等_他の権利・負担付き', '取引の事情等_他の権利・負担付き、調停・競売等',
       '取引の事情等_瑕疵有りの可能性', '取引の事情等_調停・競売等', '取引の事情等_調停・競売等、瑕疵有りの可能性',
       '取引の事情等_関係者間取引', '取引の事情等_関係者間取引、瑕疵有りの可能性', '取引の事情等_関係者間取引、調停・競売等',
       '取引の事情等_その他', '改装_改装済', '改装_未改装', '間取り_grouped_その他',
       '間取り_grouped_オープンフロア', '間取り_grouped_欠損値', '間取り_grouped_１ＤＫ',
       '間取り_grouped_１Ｋ', '間取り_grouped_１ＬＤＫ', '間取り_grouped_１Ｒ',
       '間取り_grouped_２ＤＫ', '間取り_grouped_２Ｋ', '間取り_grouped_２ＬＤＫ',
       '間取り_grouped_２ＬＤＫ＋Ｓ', '間取り_grouped_３ＤＫ', '間取り_grouped_３ＬＤＫ',
       '間取り_grouped_４ＤＫ', '間取り_grouped_４ＬＤＫ'],
      dtype='object')