## パッケージ読み込み

In [18]:
### 必要なパッケージ（ライブラリ）の読み込み ###
import pandas as pd             # データフレーム型変数を取り扱えるパッケージ"pandas"を読込み（以降"pd"と略記）
import matplotlib.pyplot as plt # グラフ描画のパッケージ"matplotlib"を読込み（以降"plt"と略記）
import seaborn as sns           # 上記matplotlibをベースにした高機能可視化モジュール"saeborn"を読込み（以降"sns"と略記）
import numpy as np              # 数値演算のためのパッケージ"numpy"を読込み（以降"np"と略記）
import japanize_matplotlib

## データ読み込み

In [19]:
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\sabri\appdata\roaming\jupyterlab-desktop\jlab_server\lib\site-packages (2.0.2)

In [20]:
import os
os.getcwd()
# The 'r' before the string makes it a "raw" string
os.chdir(r'C:\Users\sabri\Downloads\マンション価格予測\data')

In [21]:
# --- 1. 定義とパス設定 ---
PREDICT_DIR = '../data/processed_test/'
RAW_DATA_PATH = '../data//test.csv'

In [22]:
### データの読み込み ###
df_test_original= pd.read_csv('test.csv')
df_test_original

,ID,種類,地域,市区町村コード,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,間取り,...,今後の利用目的,前面道路：方位,前面道路：種類,前面道路：幅員（ｍ）,都市計画,建ぺい率（％）,容積率（％）,取引時点,改装,取引の事情等
0,1000000,中古マンション等,NaN,1101,北海道,札幌市中央区,旭ケ丘,円山公園,26,３ＬＤＫ,...,住宅,NaN,NaN,NaN,第１種低層住居専用地域,40.0,60.0,2020年第２四半期,未改装,NaN
1,1000056,中古マンション等,NaN,1101,北海道,札幌市中央区,大通西,西１１丁目,1,２ＬＤＫ,...,住宅,NaN,NaN,NaN,商業地域,80.0,600.0,2020年第１四半期,未改装,NaN
2,1000108,中古マンション等,NaN,1101,北海道,札幌市中央区,大通西,西１８丁目,2,１Ｒ,...,住宅,NaN,NaN,NaN,商業地域,80.0,400.0,2020年第２四半期,未改装,NaN
3,1000109,中古マンション等,NaN,1101,北海道,札幌市中央区,大通西,西１８丁目,2,１ＬＤＫ,...,住宅,NaN,NaN,NaN,商業地域,80.0,400.0,2020年第２四半期,改装済,NaN
4,1000110,中古マンション等,NaN,1101,北海道,札幌市中央区,大通西,西１８丁目,3,１Ｒ,...,住宅,NaN,NaN,NaN,商業地域,80.0,400.0,2020年第２四半期,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19461,47003828,中古マンション等,NaN,47208,沖縄県,浦添市,牧港,NaN,NaN,４ＬＤＫ,...,住宅,NaN,NaN,NaN,商業地域,80.0,400.0,2020年第１四半期,未改装,NaN
19462,47003829,中古マンション等,NaN,47208,沖縄県,浦添市,牧港,NaN,NaN,２ＬＤＫ,...,住宅,NaN,NaN,NaN,準工業地域,60.0,200.0,2020年第１四半期,改装済,NaN
19463,47003880,中古マンション等,NaN,47208,沖縄県,浦添市,港川,NaN,NaN,４ＬＤＫ,...,住宅,NaN,NaN,NaN,第１種中高層住居専用地域,60.0,200.0,2020年第１四半期,未改装,NaN
19464,47006648,中古マンション等,NaN,47211,沖縄県,沖縄市,与儀,NaN,NaN,３ＬＤＫ,...,住宅,NaN,NaN,NaN,市街化区域及び市街化調整区域外の都市計画区域,70.0,200.0,2020年第１四半期,未改装,NaN
19465,47007421,中古マンション等,NaN,47213,沖縄県,うるま市,字江洲,NaN,NaN,３ＬＤＫ,...,住宅,NaN,NaN,NaN,準住居地域,60.0,200.0,2020年第１四半期,未改装,NaN

In [23]:
df_test_original

,ID,種類,地域,市区町村コード,都道府県名,市区町村名,地区名,最寄駅：名称,最寄駅：距離（分）,間取り,...,今後の利用目的,前面道路：方位,前面道路：種類,前面道路：幅員（ｍ）,都市計画,建ぺい率（％）,容積率（％）,取引時点,改装,取引の事情等
0,1000000,中古マンション等,NaN,1101,北海道,札幌市中央区,旭ケ丘,円山公園,26,３ＬＤＫ,...,住宅,NaN,NaN,NaN,第１種低層住居専用地域,40.0,60.0,2020年第２四半期,未改装,NaN
1,1000056,中古マンション等,NaN,1101,北海道,札幌市中央区,大通西,西１１丁目,1,２ＬＤＫ,...,住宅,NaN,NaN,NaN,商業地域,80.0,600.0,2020年第１四半期,未改装,NaN
2,1000108,中古マンション等,NaN,1101,北海道,札幌市中央区,大通西,西１８丁目,2,１Ｒ,...,住宅,NaN,NaN,NaN,商業地域,80.0,400.0,2020年第２四半期,未改装,NaN
3,1000109,中古マンション等,NaN,1101,北海道,札幌市中央区,大通西,西１８丁目,2,１ＬＤＫ,...,住宅,NaN,NaN,NaN,商業地域,80.0,400.0,2020年第２四半期,改装済,NaN
4,1000110,中古マンション等,NaN,1101,北海道,札幌市中央区,大通西,西１８丁目,3,１Ｒ,...,住宅,NaN,NaN,NaN,商業地域,80.0,400.0,2020年第２四半期,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19461,47003828,中古マンション等,NaN,47208,沖縄県,浦添市,牧港,NaN,NaN,４ＬＤＫ,...,住宅,NaN,NaN,NaN,商業地域,80.0,400.0,2020年第１四半期,未改装,NaN
19462,47003829,中古マンション等,NaN,47208,沖縄県,浦添市,牧港,NaN,NaN,２ＬＤＫ,...,住宅,NaN,NaN,NaN,準工業地域,60.0,200.0,2020年第１四半期,改装済,NaN
19463,47003880,中古マンション等,NaN,47208,沖縄県,浦添市,港川,NaN,NaN,４ＬＤＫ,...,住宅,NaN,NaN,NaN,第１種中高層住居専用地域,60.0,200.0,2020年第１四半期,未改装,NaN
19464,47006648,中古マンション等,NaN,47211,沖縄県,沖縄市,与儀,NaN,NaN,３ＬＤＫ,...,住宅,NaN,NaN,NaN,市街化区域及び市街化調整区域外の都市計画区域,70.0,200.0,2020年第１四半期,未改装,NaN
19465,47007421,中古マンション等,NaN,47213,沖縄県,うるま市,字江洲,NaN,NaN,３ＬＤＫ,...,住宅,NaN,NaN,NaN,準住居地域,60.0,200.0,2020年第１四半期,未改装,NaN

In [24]:
#全部欠損値の行削除
df_test_original=df_test_original.dropna(axis=1,how='all')
df_test_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19466 entries, 0 to 19465
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         19466 non-null  int64
 1   種類         19466 non-null  object
 2   市区町村コード    19466 non-null  int64
 3   都道府県名      19466 non-null  object
 4   市区町村名      19466 non-null  object
 5   地区名        19463 non-null  object
 6   最寄駅：名称     19453 non-null  object
 7   最寄駅：距離（分）  19453 non-null  object
 8   間取り        18544 non-null  object
 9   面積（㎡）      19466 non-null  int64
 10  建築年        18804 non-null  object
 11  建物の構造      18201 non-null  object
 12  用途         13480 non-null  object
 13  今後の利用目的    18439 non-null  object
 14  都市計画       19122 non-null  object
 15  建ぺい率（％）    19045 non-null  float64
 16  容積率（％）     19045 non-null  float64
 17  取引時点       19466 non-null  object
 18  改装         17036 non-null  object
 19  取引の事情等     152 non-null    object
dtypes: float64(2), int64(3), object(15)
memory usage: 3.0+ MB

In [25]:
#欠損値の数確認
df_test_original.isnull().sum()

ID               0
種類               0
市区町村コード          0
都道府県名            0
市区町村名            0
地区名              3
最寄駅：名称          13
最寄駅：距離（分）       13
間取り            922
面積（㎡）            0
建築年            662
建物の構造         1265
用途            5986
今後の利用目的       1027
都市計画           344
建ぺい率（％）        421
容積率（％）         421
取引時点             0
改装            2430
取引の事情等       19314
dtype: int64

In [26]:
df_test=df_test_original.copy()
# 面積を数値型
df_test['面積（㎡）'] = df_test['面積（㎡）'].replace('2000㎡以上', 2000)
df_test['面積（㎡）']= pd.to_numeric(df_test['面積（㎡）'], errors='coerce')
#距離の数値変換と欠損値や？の削除、
df_test['最寄駅：距離（分）']= pd.to_numeric(df_test['最寄駅：距離（分）'], errors='coerce')

In [27]:
# 削除対象の列
columns_to_drop = ['種類']

# 存在を確認してから削除（エラーを防ぐため）
existing_columns = [col for col in columns_to_drop if col in df_test.columns]

if existing_columns:
    df_test = df_test.drop(columns=existing_columns)
    print(f"以下の列を削除しました: {existing_columns}")
    print(f"現在のデータフレームの列数: {len(df_test.columns)}")

print(df_test.head())

以下の列を削除しました: ['種類']
現在のデータフレームの列数: 19
        ID  市区町村コード 都道府県名   市区町村名  地区名 最寄駅：名称  最寄駅：距離（分）   間取り  面積（㎡）    建築年  \
0  1000000     1101   北海道  札幌市中央区  旭ケ丘   円山公園       26.0  ３ＬＤＫ     75  昭和64年
1  1000056     1101   北海道  札幌市中央区  大通西  西１１丁目        1.0  ２ＬＤＫ     55  平成28年
2  1000108     1101   北海道  札幌市中央区  大通西  西１８丁目        2.0    １Ｒ     15  昭和64年
3  1000109     1101   北海道  札幌市中央区  大通西  西１８丁目        2.0  １ＬＤＫ     45   平成3年
4  1000110     1101   北海道  札幌市中央区  大通西  西１８丁目        3.0    １Ｒ     20  昭和56年

  建物の構造   用途 今後の利用目的         都市計画  建ぺい率（％）  容積率（％）        取引時点   改装 取引の事情等
0    ＲＣ  NaN      住宅  第１種低層住居専用地域     40.0    60.0  2020年第２四半期  未改装    NaN
1    ＲＣ  NaN      住宅         商業地域     80.0   600.0  2020年第１四半期  未改装    NaN
2   ＳＲＣ  NaN      住宅         商業地域     80.0   400.0  2020年第２四半期  未改装    NaN
3   ＳＲＣ  NaN      住宅         商業地域     80.0   400.0  2020年第２四半期  改装済    NaN
4    ＲＣ  NaN      住宅         商業地域     80.0   400.0  2020年第２四半期  NaN    NaN

In [28]:
# --- 4. 処理後のデータを保存 ---
processed_file = 'test_cleaned.parquet'
processed_path = os.path.join(PREDICT_DIR, processed_file)

os.makedirs(PREDICT_DIR, exist_ok=True) # processed_testフォルダ作成

df_test.to_parquet(processed_path, index=False)
print(f"\n✅ クレンジング後のデータを {processed_path} (processed_test) に保存しました。")

✅ クレンジング後のデータを ../data/processed_test/test_cleaned.parquet (processed_test) に保存しました。